site_name: School book market
repo_url: https://github.com/Xantus10/MATURITA
edit_uri: edit/master/doc/development-doc/docs/
nav:
  - Home: index.md
  - Technologies: tech.md
  - Flow overview: flow.md
  - Directory structure: dir.md
  - Running the app: run.md
  - Adding features: add.md
  - Security: security.md
theme: readthedocs
use_directory_urls: false